# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(673, 436)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(300, 380, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 601, 320))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.v_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.v_layout.setContentsMargins(0, 0, 0, 0)
        self.v_layout.setObjectName("v_layout")
        self.title_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.v_layout.addWidget(self.title_label)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.v_layout.addItem(spacerItem)
        self.g_layout = QtWidgets.QGridLayout()
        self.g_layout.setObjectName("g_layout")
        self.pushnotif_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.pushnotif_cb.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(38)
        sizePolicy.setHeightForWidth(self.pushnotif_cb.sizePolicy().hasHeightForWidth())
        self.pushnotif_cb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushnotif_cb.setFont(font)
        self.pushnotif_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushnotif_cb.setAutoFillBackground(False)
        self.pushnotif_cb.setText("")
        self.pushnotif_cb.setObjectName("pushnotif_cb")
        self.g_layout.addWidget(self.pushnotif_cb, 0, 1, 1, 1)
        self.emailnotif_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.emailnotif_cb.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(38)
        sizePolicy.setHeightForWidth(self.emailnotif_cb.sizePolicy().hasHeightForWidth())
        self.emailnotif_cb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.emailnotif_cb.setFont(font)
        self.emailnotif_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.emailnotif_cb.setAutoFillBackground(False)
        self.emailnotif_cb.setText("")
        self.emailnotif_cb.setObjectName("emailnotif_cb")
        self.g_layout.addWidget(self.emailnotif_cb, 1, 1, 1, 1)
        self.emailnotif_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.emailnotif_label.setFont(font)
        self.emailnotif_label.setObjectName("emailnotif_label")
        self.g_layout.addWidget(self.emailnotif_label, 1, 0, 1, 1)
        self.pushnotif_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushnotif_label.setFont(font)
        self.pushnotif_label.setObjectName("pushnotif_label")
        self.g_layout.addWidget(self.pushnotif_label, 0, 0, 1, 1)
        self.v_layout.addLayout(self.g_layout)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.v_layout.addItem(spacerItem1)
        self.emailadd_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.emailadd_label.setFont(font)
        self.emailadd_label.setObjectName("emailadd_label")
        self.v_layout.addWidget(self.emailadd_label)
        self.email_le = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_le.sizePolicy().hasHeightForWidth())
        self.email_le.setSizePolicy(sizePolicy)
        self.email_le.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.email_le.setFont(font)
        self.email_le.setObjectName("email_le")
        self.v_layout.addWidget(self.email_le)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_label.setText(_translate("Dialog", "Notification Settings"))
        self.emailnotif_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Enable email notifications</span></p></body></html>"))
        self.pushnotif_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Enable push notifications</span></p></body></html>"))
        self.emailadd_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Send emails to this address:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

